services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lengofy-app
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - /var/www/html/node_modules
    ports:
      - "9000:9000"
      - "5173:5173"  # Vite dev server port
      - "6001:6001"  # Bun WebSocket port
    networks:
      - lengofy-network
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: ${APP_KEY}
      APP_URL: http://localhost
      VITE_APP_URL: http://localhost:5173

  webserver:
    image: nginx:latest
    container_name: nginx
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    depends_on:
      - app
    networks:
      - lengofy-network

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - lengofy-network

volumes:
  dbdata:

networks:
  lengofy-network:
    driver: bridge
